# platform :ios, '12.0'

# target 'Runner' do
#   use_frameworks!

#   # Flutter SDK dependencies
#   flutter_root = '/Users/macbookpro2015/Documents/flutter'  # Adjust path as per your Flutter installation
#   pod 'Flutter', :path => "#{flutter_root}/packages/flutter"

#   # Generated dependency from Flutter plugins
#   pod 'GeneratedPluginRegistrant', :path => "#{flutter_root}/packages/flutter_tools"

#   # Add your pods here
#   # pod 'Firebase/Core'  # Example pod

# end

